### ISSUE TITLE
bug cuase by bi_pos_discount/models/pos.py     

### ISSUE THREAD

**Issue by abudulalibayo** [abudulalibayo/alshomous#3]
![Screenshot from 2020-02-26 06-18-19](https://user-images.githubusercontent.com/27553992/75340112-d95b5400-585f-11ea-978f-e48e5abb86ff.png)

**Comment by abudulalibayo** [comment]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 2028, in report_download
    response = self.report_routes(reportname, converter=converter, context=context, **data)
  File "/home/odoo/src/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1959, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 718, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/home/odoo/src/enterprise/web_studio/models/ir_actions_report.py", line 18, in render_qweb_html
    return super(IrActionsReport, self).render_qweb_html(docids, data)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 757, in render_qweb_html
    data = self._get_rendering_context(docids, data)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 774, in _get_rendering_context
    data.update(report_model._get_report_values(docids, data=data))
  File "/home/odoo/src/odoo/addons/point_of_sale/models/pos_order.py", line 978, in _get_report_values
    data.update(self.get_sale_details(data['date_start'], data['date_stop'], configs.ids))
  File "/home/odoo/src/user/bi_pos_discount-13.0.0.0/bi_pos_discount/models/pos.py", line 228, in get_sale_details
    ('config_id', 'in', configs.ids)])
AttributeError: 'list' object has no attribute 'ids'

**Comment by NirajPajwani** [comment]
Done
