### ISSUE TITLE
Error: Point of sale > orders > Sessions

### ISSUE THREAD

**Issue by NirajPajwani** [abudulalibayo/alshomous#4]
When we print the session summary report, will get an error:

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 2021, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/home/odoo/src/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1959, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 723, in render_qweb_pdf
    bodies, html_ids, header, footer, specific_paperformat_args = self.with_context(context)._prepare_html(html)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 354, in _prepare_html
    body_parent = root.xpath('//main')[0]
IndexError: list index out of range

**Comment by NirajPajwani** [comment]
Done.
